name: Generate Snake Animation # by github.com/Platane/snk
on:
  schedule: # execute new image every 6 hours
    - cron: "* */6 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Configuration of Snake Animation
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: jedington
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}