# by github.com/Platane/snk -- check their repo out!
name: Generate Snake Animation
on:
  schedule: # refresh every 12 hours; not necessary as 'push' is used, but w/e
    - cron: "* */12 * * *"
  workflow_dispatch: # not used
  push: # refreshes for every push to master/main branches
    branches:
      - master
      - main
      - dev
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}